remote_theme: daattali/beautiful-jekyll

title: JV Sports

author: JV Sports Ltd

avatar: "/assets/img/jvlogo.jpg"
# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

navbar-links:

  About Us: "/#aboutus"
  Contact Us: "/contact"

title-img: /assets/img/jvsportslogo.jpg

site-css: "/assets/css/jvsports.css"
google_analytics: "UA-209825518-1"

keywords: "Mercedes, Consultancy, Racing, Motorsport, GT Racing, GT3, GT4, LMP3, Formula 1, F1"

mobile-theme-col: "#0085A1"
navbar-col: "#05172d"
navbar-text-col: "#fff"
navbar-border-col: "#05172d"

social-network-links:
  email: "info@jv-sports.com"
  twitter: jv_f1
  linkedin: james-vowles-17465664

url-pretty: "jv-sports.com"

footer-img: "/assets/img/footer-bg.png"

#google_analytics: "UA-59820529-1"

timezone: "Europe/Lndon"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      footer-extra: custom_footer.html
      nav-short: true
      share-description: "JV Sports - Competitive FIA Bonza Driver."
      share-img: "/assets/img/jvlogo.jpg"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md


plugins:
  - jekyll-paginate
  - jekyll-sitemap
